// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=../mocks/rest_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/ilam072/shortener/internal/click/types/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockClick is a mock of Click interface.
type MockClick struct {
	ctrl     *gomock.Controller
	recorder *MockClickMockRecorder
	isgomock struct{}
}

// MockClickMockRecorder is the mock recorder for MockClick.
type MockClickMockRecorder struct {
	mock *MockClick
}

// NewMockClick creates a new mock instance.
func NewMockClick(ctrl *gomock.Controller) *MockClick {
	mock := &MockClick{ctrl: ctrl}
	mock.recorder = &MockClickMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClick) EXPECT() *MockClickMockRecorder {
	return m.recorder
}

// GetClicksSummary mocks base method.
func (m *MockClick) GetClicksSummary(ctx context.Context, alias string) (dto.GetClicks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClicksSummary", ctx, alias)
	ret0, _ := ret[0].(dto.GetClicks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClicksSummary indicates an expected call of GetClicksSummary.
func (mr *MockClickMockRecorder) GetClicksSummary(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClicksSummary", reflect.TypeOf((*MockClick)(nil).GetClicksSummary), ctx, alias)
}
