// Code generated by MockGen. DO NOT EDIT.
// Source: click.go
//
// Generated by this command:
//
//	mockgen -source=click.go -destination=../mocks/service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ilam072/shortener/internal/click/types/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClickRepo is a mock of ClickRepo interface.
type MockClickRepo struct {
	ctrl     *gomock.Controller
	recorder *MockClickRepoMockRecorder
	isgomock struct{}
}

// MockClickRepoMockRecorder is the mock recorder for MockClickRepo.
type MockClickRepoMockRecorder struct {
	mock *MockClickRepo
}

// NewMockClickRepo creates a new mock instance.
func NewMockClickRepo(ctrl *gomock.Controller) *MockClickRepo {
	mock := &MockClickRepo{ctrl: ctrl}
	mock.recorder = &MockClickRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickRepo) EXPECT() *MockClickRepoMockRecorder {
	return m.recorder
}

// CreateClick mocks base method.
func (m *MockClickRepo) CreateClick(ctx context.Context, click domain.Click) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClick", ctx, click)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClick indicates an expected call of CreateClick.
func (mr *MockClickRepoMockRecorder) CreateClick(ctx, click any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClick", reflect.TypeOf((*MockClickRepo)(nil).CreateClick), ctx, click)
}

// GetClicksByDay mocks base method.
func (m *MockClickRepo) GetClicksByDay(ctx context.Context, alias string) ([]domain.ClickRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClicksByDay", ctx, alias)
	ret0, _ := ret[0].([]domain.ClickRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClicksByDay indicates an expected call of GetClicksByDay.
func (mr *MockClickRepoMockRecorder) GetClicksByDay(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClicksByDay", reflect.TypeOf((*MockClickRepo)(nil).GetClicksByDay), ctx, alias)
}

// GetClicksByMonth mocks base method.
func (m *MockClickRepo) GetClicksByMonth(ctx context.Context, alias string) ([]domain.ClickRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClicksByMonth", ctx, alias)
	ret0, _ := ret[0].([]domain.ClickRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClicksByMonth indicates an expected call of GetClicksByMonth.
func (mr *MockClickRepoMockRecorder) GetClicksByMonth(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClicksByMonth", reflect.TypeOf((*MockClickRepo)(nil).GetClicksByMonth), ctx, alias)
}

// GetClicksByUserAgent mocks base method.
func (m *MockClickRepo) GetClicksByUserAgent(ctx context.Context, alias string) ([]domain.ClickRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClicksByUserAgent", ctx, alias)
	ret0, _ := ret[0].([]domain.ClickRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClicksByUserAgent indicates an expected call of GetClicksByUserAgent.
func (mr *MockClickRepoMockRecorder) GetClicksByUserAgent(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClicksByUserAgent", reflect.TypeOf((*MockClickRepo)(nil).GetClicksByUserAgent), ctx, alias)
}
