// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=../mocks/rest_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/ilam072/shortener/internal/click/types/dto"
	dto0 "github.com/ilam072/shortener/internal/link/types/dto"
	retry "github.com/wb-go/wbf/retry"
	gomock "go.uber.org/mock/gomock"
)

// MockLink is a mock of Link interface.
type MockLink struct {
	ctrl     *gomock.Controller
	recorder *MockLinkMockRecorder
	isgomock struct{}
}

// MockLinkMockRecorder is the mock recorder for MockLink.
type MockLinkMockRecorder struct {
	mock *MockLink
}

// NewMockLink creates a new mock instance.
func NewMockLink(ctrl *gomock.Controller) *MockLink {
	mock := &MockLink{ctrl: ctrl}
	mock.recorder = &MockLinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLink) EXPECT() *MockLinkMockRecorder {
	return m.recorder
}

// GetURLByAlias mocks base method.
func (m *MockLink) GetURLByAlias(ctx context.Context, alias string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLByAlias", ctx, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLByAlias indicates an expected call of GetURLByAlias.
func (mr *MockLinkMockRecorder) GetURLByAlias(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLByAlias", reflect.TypeOf((*MockLink)(nil).GetURLByAlias), ctx, alias)
}

// SaveLink mocks base method.
func (m *MockLink) SaveLink(ctx context.Context, link dto0.Link, strategy retry.Strategy) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLink", ctx, link, strategy)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveLink indicates an expected call of SaveLink.
func (mr *MockLinkMockRecorder) SaveLink(ctx, link, strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLink", reflect.TypeOf((*MockLink)(nil).SaveLink), ctx, link, strategy)
}

// MockClick is a mock of Click interface.
type MockClick struct {
	ctrl     *gomock.Controller
	recorder *MockClickMockRecorder
	isgomock struct{}
}

// MockClickMockRecorder is the mock recorder for MockClick.
type MockClickMockRecorder struct {
	mock *MockClick
}

// NewMockClick creates a new mock instance.
func NewMockClick(ctrl *gomock.Controller) *MockClick {
	mock := &MockClick{ctrl: ctrl}
	mock.recorder = &MockClickMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClick) EXPECT() *MockClickMockRecorder {
	return m.recorder
}

// SaveClick mocks base method.
func (m *MockClick) SaveClick(ctx context.Context, click dto.Click) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveClick", ctx, click)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveClick indicates an expected call of SaveClick.
func (mr *MockClickMockRecorder) SaveClick(ctx, click any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveClick", reflect.TypeOf((*MockClick)(nil).SaveClick), ctx, click)
}

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockValidator) Validate(i any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockValidatorMockRecorder) Validate(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidator)(nil).Validate), i)
}
