// Code generated by MockGen. DO NOT EDIT.
// Source: link.go
//
// Generated by this command:
//
//	mockgen -source=link.go -destination=../mocks/service_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ilam072/shortener/internal/link/types/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkRepo is a mock of LinkRepo interface.
type MockLinkRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepoMockRecorder
	isgomock struct{}
}

// MockLinkRepoMockRecorder is the mock recorder for MockLinkRepo.
type MockLinkRepoMockRecorder struct {
	mock *MockLinkRepo
}

// NewMockLinkRepo creates a new mock instance.
func NewMockLinkRepo(ctrl *gomock.Controller) *MockLinkRepo {
	mock := &MockLinkRepo{ctrl: ctrl}
	mock.recorder = &MockLinkRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepo) EXPECT() *MockLinkRepoMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockLinkRepo) CreateLink(ctx context.Context, link domain.Link) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ctx, link)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockLinkRepoMockRecorder) CreateLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockLinkRepo)(nil).CreateLink), ctx, link)
}

// GetURLByAlias mocks base method.
func (m *MockLinkRepo) GetURLByAlias(ctx context.Context, alias string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLByAlias", ctx, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLByAlias indicates an expected call of GetURLByAlias.
func (mr *MockLinkRepoMockRecorder) GetURLByAlias(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLByAlias", reflect.TypeOf((*MockLinkRepo)(nil).GetURLByAlias), ctx, alias)
}

// MockLinkCache is a mock of LinkCache interface.
type MockLinkCache struct {
	ctrl     *gomock.Controller
	recorder *MockLinkCacheMockRecorder
	isgomock struct{}
}

// MockLinkCacheMockRecorder is the mock recorder for MockLinkCache.
type MockLinkCacheMockRecorder struct {
	mock *MockLinkCache
}

// NewMockLinkCache creates a new mock instance.
func NewMockLinkCache(ctrl *gomock.Controller) *MockLinkCache {
	mock := &MockLinkCache{ctrl: ctrl}
	mock.recorder = &MockLinkCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkCache) EXPECT() *MockLinkCacheMockRecorder {
	return m.recorder
}

// GetURL mocks base method.
func (m *MockLinkCache) GetURL(ctx context.Context, alias string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", ctx, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURL indicates an expected call of GetURL.
func (mr *MockLinkCacheMockRecorder) GetURL(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockLinkCache)(nil).GetURL), ctx, alias)
}

// SetURL mocks base method.
func (m *MockLinkCache) SetURL(ctx context.Context, alias, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetURL", ctx, alias, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetURL indicates an expected call of SetURL.
func (mr *MockLinkCacheMockRecorder) SetURL(ctx, alias, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetURL", reflect.TypeOf((*MockLinkCache)(nil).SetURL), ctx, alias, url)
}
