// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/analytics/{alias}": {
            "get": {
                "description": "Возвращает статистику кликов по alias: по дням, месяцам и user-agent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Получить аналитику по ссылке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Alias ссылки",
                        "name": "alias",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Статистика кликов",
                        "schema": {
                            "$ref": "#/definitions/dto.GetClicks"
                        }
                    },
                    "400": {
                        "description": "alias must not be empty",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/s/{alias}": {
            "get": {
                "description": "Перенаправляет пользователя на оригинальный URL по alias и сохраняет информацию о клике",
                "tags": [
                    "Links"
                ],
                "summary": "Редирект по короткой ссылке",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Alias ссылки",
                        "name": "alias",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to original URL"
                    },
                    "400": {
                        "description": "alias must not be empty",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "alias not found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/shorten": {
            "post": {
                "description": "Создаёт новую короткую ссылку. Alias можно передать вручную или он будет сгенерирован автоматически",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Links"
                ],
                "summary": "Создать короткую ссылку",
                "parameters": [
                    {
                        "description": "Данные для создания ссылки",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Link"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "alias созданной ссылки",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "invalid request body или validation error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "409": {
                        "description": "alias already exists",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ClicksByDay": {
            "type": "object",
            "properties": {
                "clicks": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                }
            }
        },
        "dto.ClicksByMonth": {
            "type": "object",
            "properties": {
                "clicks": {
                    "type": "integer"
                },
                "month": {
                    "type": "string"
                }
            }
        },
        "dto.ClicksByUserAgent": {
            "type": "object",
            "properties": {
                "clicks": {
                    "type": "integer"
                },
                "user_agent": {
                    "type": "string"
                }
            }
        },
        "dto.GetClicks": {
            "type": "object",
            "properties": {
                "alias": {
                    "type": "string"
                },
                "by_day": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ClicksByDay"
                    }
                },
                "by_month": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ClicksByMonth"
                    }
                },
                "by_user_agent": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ClicksByUserAgent"
                    }
                }
            }
        },
        "dto.Link": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "alias": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "payload": {},
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Shortener API",
	Description:      "REST API сервиса сокращения ссылок с аналитикой кликов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
